site_name: Scruffy Wiki

nav:
  - Home: index.md

  - Bandar Esok: 
    - notes/bandarEsokLore/

  - Solo Journalling Games: 

    - Caveat Emptor:
      - notes/caveatEmptor/

    - Ex Novo:
      - notes/exNovo/

  - Webdev Notes:
    - notes/webdevNotes/

  - Gamedev Notes:
    - notes/gamedevNotes/

  - Ideas/Concepts:
    - notes/ideas/


extra_css:
  - stylesheets/extra.css
  
theme: 
  logo: media/notebook-heart.svg
  name: material
  favicon: media/gaston-head.png
  palette:
    primary: teal
    accent: deep orange
  features:
    - navigation.indexes 

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - include_dir_to_nav