site_name: Scruffy Wiki

nav:
  - Home: index.md

  - Bandar Esok: 
    - Snippets: 
      - 年兽's influence: notes/bandarEsokLore/snippets/年兽-influence.md
      - Restoran Laut Brainstorm: notes/bandarEsokLore/snippets/restoran-laut-brainstorm.md

  - Solo Journalling Games: 

    - Caveat Emptor:
      - Intro: 
        - The Game: notes/caveatEmptor/Caveat Emptor.md
        - Notes on the Boss: notes/caveatEmptor/Notes on the Boss (Mephistopheles).md
      - Game#1: notes/caveatEmptor/game#1/Day#1.md

    - Ex Novo:
      - Game#1: 
        - Bandar Esok (ver.1): notes/exNovo/game#1/bandar-esok-ver-1.md
        - Events: notes/exNovo/game#1/Events.md

  - Personal Webdev Notes:
    - The Odin Project: notes/webdevNotes/the-odin-project.md
    - Using MkDocs: notes/webdevNotes/using-mkdocs.md


theme: material
# features:
#     - navigation.instant (needs url)