site_name: Scruffy Wiki

nav:
  - Home: index.md

  - Bandar Esok: 
    - Snippets: 
      - notes/bandarEsokLore/snippets/年兽-influence.md
      - notes/bandarEsokLore/snippets/restoran-laut-brainstorm.md

  - Solo Journalling Games: 

    - Caveat Emptor:
      - Intro: 
        - notes/caveatEmptor/Caveat Emptor.md
        - notes/caveatEmptor/Notes on the Boss (Mephistopheles).md
      - notes/caveatEmptor/game#1/Day#1.md

    - Ex Novo:
      - Game#1: 
        - notes/exNovo/game#1/bandar-esok-ver-1.md
        - notes/exNovo/game#1/Events.md

  - Personal Webdev Notes:
    - notes/webdevNotes/the-odin-project.md
    - notes/webdevNotes/using-mkdocs.md
    - notes/webdevNotes/on-digital-gardens.md


theme: material
# features:
#     - navigation.instant (needs url)